name: PHP Composer

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Show PHP Version
        run: php -v

      - name: Add Phalcon package repository
        run: curl -s https://packagecloud.io/install/repositories/phalcon/mainline/script.deb.sh | sudo bash

      - name: Install Phalcon
        run: sudo apt-get install php7.3-phalcon

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: vendor/bin/phpunit tests/Unit/Utils/NullifyTest.php
