name: PHP Composer

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - uses: actions/checkout@v1

      - name: Init Database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS phalcon-migrations;'

      - name: Show PHP Version
        run: php -v

      - name: Add Phalcon package repository
        run: curl -s https://packagecloud.io/install/repositories/phalcon/mainline/script.deb.sh | sudo bash

      - name: Install PSR PECL Package
        run: sudo apt-get install php-pear && sudo pecl install --force psr

      - name: Install Phalcon
        run: sudo apt-get install php7.3-phalcon

      - name: Enable PHP PSR Extension
        run: echo 'extension=psr.so' | sudo tee -a /etc/php/7.3/mods-available/phalcon.ini && cat /etc/php/7.3/mods-available/phalcon.ini

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: vendor/bin/phpunit

      - name: Run Psalm
        run: vendor/bin/psalm --show-info=false
